language: python
    python:
      - "3.5"
    services:
      - postgresql
    env:
      -DJANGO=2.2.2 DB=postgresql
    install:
      - pip install -r requirements.txt
    before_script:
      - postgresql -e 'create database chat_room;' -u root
    script:
      - python manage.py test
