language: python
python: '3.6'
before_install: # or any other customizable place
  - source ~/virtualenv/python3.5/bin/activate
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
